/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import model.PersonProfile;

/**
 *
 * @author fianrodrigues
 */
public class CreateProfileJPanel extends javax.swing.JPanel 
{
    /**
     * Creates new form CreateProfileJPanel
     */
    PersonProfile person;
    public CreateProfileJPanel(PersonProfile person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLicenseNum = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lbPlateNum = new javax.swing.JLabel();
        lbDeviceNum = new javax.swing.JLabel();
        lbLinkedIn = new javax.swing.JLabel();
        lbIPAddress = new javax.swing.JLabel();
        txtGeoData = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtTelNum = new javax.swing.JTextField();
        txtFAXNum = new javax.swing.JTextField();
        txtEmailAdd = new javax.swing.JTextField();
        lbGeographicData = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lbDOB = new javax.swing.JLabel();
        txtMedRecNum = new javax.swing.JTextField();
        lbTelephoneNum = new javax.swing.JLabel();
        txtHPBNum = new javax.swing.JTextField();
        lbFaxNum = new javax.swing.JLabel();
        txtBankAccNum = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        lbSSN = new javax.swing.JLabel();
        lbMedicalRecNum = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtPlateNum = new javax.swing.JTextField();
        txtDeviceIdentifier = new javax.swing.JTextField();
        lbHPBNum = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JTextField();
        lbAccNum = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lbIDCode = new javax.swing.JLabel();
        txtIDCode = new javax.swing.JTextField();
        lbImgSubmit = new javax.swing.JLabel();
        btnImgSubmit = new javax.swing.JButton();
        lbPhoto = new javax.swing.JLabel();
        lbErr = new javax.swing.JLabel();
        lbBioVal = new javax.swing.JLabel();
        btnBioVal = new javax.swing.JButton();
        lbBioImg = new javax.swing.JLabel();

        lbLicenseNum.setText("License Number:");

        lbTitle.setText("CREATE PROFILE");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbPlateNum.setText("License Plate Number:");

        lbDeviceNum.setText("Device Identifier:");

        lbLinkedIn.setText("LinkedIn:");

        lbIPAddress.setText("IP Address:");

        txtGeoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoDataActionPerformed(evt);
            }
        });
        txtGeoData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGeoDataKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeoDataKeyTyped(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        txtDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDOBKeyTyped(evt);
            }
        });

        txtTelNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNumActionPerformed(evt);
            }
        });
        txtTelNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelNumKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelNumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelNumKeyTyped(evt);
            }
        });

        txtFAXNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXNumActionPerformed(evt);
            }
        });
        txtFAXNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFAXNumKeyTyped(evt);
            }
        });

        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });
        txtEmailAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailAddKeyTyped(evt);
            }
        });

        lbGeographicData.setText("Location:");

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSSNKeyTyped(evt);
            }
        });

        lbDOB.setText("Date of Birth:");

        txtMedRecNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedRecNumActionPerformed(evt);
            }
        });
        txtMedRecNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedRecNumKeyTyped(evt);
            }
        });

        lbTelephoneNum.setText("Tel. Number:");

        txtHPBNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPBNumActionPerformed(evt);
            }
        });
        txtHPBNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHPBNumKeyTyped(evt);
            }
        });

        lbFaxNum.setText("FAX Number:");

        txtBankAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccNumActionPerformed(evt);
            }
        });
        txtBankAccNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBankAccNumKeyTyped(evt);
            }
        });

        lbEmail.setText("E-Mail Address:");

        txtLicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumActionPerformed(evt);
            }
        });
        txtLicenseNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLicenseNumKeyTyped(evt);
            }
        });

        lbSSN.setText("Social Security Number:");

        lbMedicalRecNum.setText("Medical Record Number:");

        lbName.setText("Name");

        txtPlateNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlateNumActionPerformed(evt);
            }
        });
        txtPlateNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlateNumKeyTyped(evt);
            }
        });

        txtDeviceIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdentifierActionPerformed(evt);
            }
        });
        txtDeviceIdentifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeviceIdentifierKeyTyped(evt);
            }
        });

        lbHPBNum.setText("Health Plan Beneficiary Number:");

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyTyped(evt);
            }
        });

        lbAccNum.setText("Bank Account Number:");

        txtIPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddressActionPerformed(evt);
            }
        });
        txtIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIPAddressKeyTyped(evt);
            }
        });

        lbIDCode.setText("Unique Indentifying Code:");

        txtIDCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCodeActionPerformed(evt);
            }
        });
        txtIDCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDCodeKeyTyped(evt);
            }
        });

        lbImgSubmit.setText("Photo Identification:");

        btnImgSubmit.setText("Upload ");
        btnImgSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgSubmitActionPerformed(evt);
            }
        });

        lbErr.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lbErr.setForeground(new java.awt.Color(255, 51, 51));

        lbBioVal.setText("Biometric Validation:");

        btnBioVal.setText("Upload ");
        btnBioVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBioValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFaxNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFAXNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSSN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMedicalRecNum)
                        .addGap(121, 121, 121)
                        .addComponent(lbErr, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbHPBNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAccNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLicenseNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPlateNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPlateNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDeviceNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLinkedIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIPAddress)
                            .addComponent(lbIDCode)
                            .addComponent(lbImgSubmit)
                            .addComponent(lbBioVal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnSave)))
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbBioImg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImgSubmit)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                .addComponent(txtIDCode))
                            .addComponent(btnBioVal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTelephoneNum)
                        .addGap(526, 526, 526)
                        .addComponent(txtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbGeographicData)
                            .addComponent(lbDOB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGeographicData)
                    .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTelephoneNum)
                            .addComponent(txtTelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFaxNum)
                            .addComponent(txtFAXNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSSN)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbMedicalRecNum)
                                .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbErr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHPBNum)
                            .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAccNum)
                            .addComponent(txtBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLicenseNum)
                            .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPlateNum)
                            .addComponent(txtPlateNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDeviceNum)
                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLinkedIn)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIPAddress)
                            .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbIDCode))
                    .addComponent(txtIDCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImgSubmit)
                    .addComponent(btnImgSubmit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBioVal)
                    .addComponent(btnBioVal)
                    .addComponent(lbBioImg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
     
          
person.setName(txtName.getText());
person.setGeographicalData(txtGeoData.getText());
person.setDateOfBirth(txtDOB.getText());
person.setEmailAddress(txtEmailAdd.getText());
person.setDeviceIdentifier(txtDeviceIdentifier.getText());
person.setLinkedinLink(txtLinkedIn.getText());
try
{
    //person.setDateOfBirth(String.valueOf(txtDOB.getText()));
  person.setTelephoneNumber(Long.parseLong(txtTelNum.getText()));
person.setFaxNumber(Long.parseLong(txtFAXNum.getText()));
person.setSocialSecurityNumber(Integer.parseInt(txtSSN.getText()));
person.setMedicalRecordNumber(Long.parseLong(txtMedRecNum.getText()));
person.setBeneficiaryNumber(Long.parseLong(txtHPBNum.getText()));
person.setAccountNumber(Long.parseLong(txtBankAccNum.getText()));
person.setLicenseNumber(Long.parseLong(txtLicenseNum.getText()));
person.setPlateNumber(String.valueOf(txtPlateNum.getText()));
person.setIPAddress(txtIPAddress.getText());
person.setIndentifyingnum(Long.parseLong(txtIDCode.getText()));
} catch(NumberFormatException ex){ 
// handle your exception
            ex.printStackTrace();
        }

JOptionPane.showMessageDialog(this, "Person Information Saved");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtGeoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoDataActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtTelNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumActionPerformed

    private void txtFAXNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXNumActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtMedRecNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedRecNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedRecNumActionPerformed

    private void txtHPBNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPBNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPBNumActionPerformed

    private void txtBankAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccNumActionPerformed

    private void txtLicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumActionPerformed

    private void txtPlateNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlateNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlateNumActionPerformed

    private void txtDeviceIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtIPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddressActionPerformed

    private void txtIDCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCodeActionPerformed

    private void btnImgSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgSubmitActionPerformed
        // TODO add your handling code here:
       JFileChooser filechooser = new JFileChooser();
    filechooser.setDialogTitle("Select Your File");
    filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int returnval = filechooser.showOpenDialog(this);
    if (returnval == JFileChooser.APPROVE_OPTION)
    {
        File file = filechooser.getSelectedFile();
        BufferedImage bi;
        BufferedImage img = null;
        try {
            // display the image in a Jlabel
            bi = ImageIO.read(file);
            
            Image dimg = bi.getScaledInstance(lbPhoto.getWidth(),lbPhoto.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);
            lbPhoto.setIcon(icon);
            person.setPicture(icon);
        } catch(IOException e) {
           e.printStackTrace(); // todo: implement proper error handeling
        }
    }
    }//GEN-LAST:event_btnImgSubmitActionPerformed

// ignore the following code//
    private void txtGeoDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeoDataKeyReleased

    }//GEN-LAST:event_txtGeoDataKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameKeyReleased
//ignore the above code//
    
    
    private void btnBioValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBioValActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
    filechooser.setDialogTitle("Select Your File");
    filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int returnval = filechooser.showOpenDialog(this);
    if (returnval == JFileChooser.APPROVE_OPTION)
    {
        File file = filechooser.getSelectedFile();
        BufferedImage bi;
        BufferedImage img = null;
        try {
            // display the image in a Jlabel
            bi = ImageIO.read(file);
            Image dimg = bi.getScaledInstance(lbBioImg.getWidth(),lbBioImg.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);
            lbBioImg.setIcon(icon);
            person.setPicture(icon);
        } catch(IOException e) {
           e.printStackTrace(); // todo: implement proper error handeling
        }
    }
    }//GEN-LAST:event_btnBioValActionPerformed

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
          
           if(Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c)){
               txtName.setEditable(true);
           }else {
               if(!Character.isLetter(c)){
                lbErr.setText(" ");
               }
                else
        {
            lbErr.setText("Invalid Input!!");
        }
           }
    }//GEN-LAST:event_txtNameKeyTyped

    
    // ignore this section//
    
    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtTelNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyReleased
        // TODO add your handling code here
     
    }//GEN-LAST:event_txtTelNumKeyReleased

    private void txtTelNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNumKeyPressed

    //Ignore the above section//
    
    private void txtTelNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelNumKeyTyped
        // TODO add your handling code here:
        String phoneNumber = txtTelNum.getText();
        int l = phoneNumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(l<10)
            {
                txtTelNum.setEditable(true);
                lbErr.setText("Input should be 10 digits");
            }
            else
            {
                txtTelNum.setEditable(false);
                lbErr.setText("Ivalid Phone Number");
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtTelNum.setEditable(true);
            }
            else
            {
                txtTelNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtTelNumKeyTyped

    private void txtDOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBKeyTyped
        // TODO add your handling code here:
        String dobirth = "^[0-9]{0,2}-[0-9]{0,2}-[0-9]{0,4}+";
        Pattern dob = Pattern.compile(dobirth);
        Matcher matcher = dob.matcher(txtDOB.getText());
        if(!matcher.matches())
        {
        lbErr.setText("Input invalid!");
        }
        else
        {
            lbErr.setText(" ");
        }
    }//GEN-LAST:event_txtDOBKeyTyped

    private void txtGeoDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeoDataKeyTyped
        // TODO add your handling code here:
        String add = "[A-Za-z0-9\\s,\\.#]+";
        Pattern geod = Pattern.compile(add);
        Matcher matcher = geod.matcher(txtGeoData.getText());
        if(!matcher.matches())
        {
        lbErr.setText("Input invalid!");
        }
        else
        {
            lbErr.setText(" ");
        }
    }//GEN-LAST:event_txtGeoDataKeyTyped

    private void txtFAXNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFAXNumKeyTyped
        // TODO add your handling code here:
        String faxNumber = txtFAXNum.getText();
        int length = faxNumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<10)
            {
                txtFAXNum.setEditable(true);
                lbErr.setText("Input should be 10 digits");
            }
            else
            {
                txtFAXNum.setEditable(false);
                lbErr.setText(" ");
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtFAXNum.setEditable(true);
            }
            else
            {
                txtFAXNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtFAXNumKeyTyped

    private void txtLinkedInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyTyped
        // TODO add your handling code here:
        String li = "^https:\\/\\/[a-z]{2,3}\\.linkedin\\.com\\/.*";
        Pattern exp = Pattern.compile(li);
        Matcher match = exp.matcher(txtLinkedIn.getText());
        if(!match.matches())
    {
        lbErr.setText("Input invalid!");
    }
    else
    {
        lbErr.setText("  ");
    }
    }//GEN-LAST:event_txtLinkedInKeyTyped

    private void txtPlateNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlateNumKeyTyped
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,7}+";
        Pattern exp = Pattern.compile(PATTERN);
        Matcher match = exp.matcher(txtName.getText());
        if(!match.matches()){
            lbErr.setText("Input invalid!");
        }else{   
            lbErr.setText(" ");
        }
    }//GEN-LAST:event_txtPlateNumKeyTyped

    private void txtEmailAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddKeyTyped
        // TODO add your handling code here:
        String emreg = "^[a-zA-Z0-9]+@[a-zA-Z]+\\.[a-zA-Z]+";
        Pattern ep = Pattern.compile(emreg);
        Matcher matcher = ep.matcher(txtEmailAdd.getText());
        if(!matcher.matches())
        {
        lbErr.setText("Input invalid!");
        }
        else
        {
            lbErr.setText(" ");
        }
    }//GEN-LAST:event_txtEmailAddKeyTyped

    private void txtSSNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyTyped
        // TODO add your handling code here:
        
        String ssn = txtSSN.getText();
        int length = ssn.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
          if(length<9)
          {
           txtSSN.setEditable(true);
           lbErr.setText("Input should be 9 digits");
          }
        else
          {
           txtSSN.setEditable(false);
           lbErr.setText("Input invalid!");
          }
        }
        else 
        {
          if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
          txtSSN.setEditable(true);
        }
          else
          {
           txtSSN.setEditable(false);
          }
}
    }//GEN-LAST:event_txtSSNKeyTyped

    private void txtMedRecNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedRecNumKeyTyped
        // TODO add your handling code here:
       String medrec = txtMedRecNum.getText();
        int leng = medrec.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='6'){
            if(leng<=7){
                txtMedRecNum.setEditable(true);
                 lbErr.setText("Input should be 7 digits");
            }else{
                txtMedRecNum.setEditable(false);
                lbErr.setText(" ");
            }
        }else {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtMedRecNum.setEditable(true);
            }else{
                txtMedRecNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtMedRecNumKeyTyped

    private void txtHPBNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHPBNumKeyTyped
        // TODO add your handling code here:
        String hpbn = txtHPBNum.getText();
        int length = hpbn.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='6'){
            if(length<=7){
                txtHPBNum.setEditable(true);
                 lbErr.setText("Input should be 7 digits");
            }else{
                txtHPBNum.setEditable(false);
                lbErr.setText(" ");
            }
        }else {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtHPBNum.setEditable(true);
            }else{
                txtHPBNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtHPBNumKeyTyped

    private void txtBankAccNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccNumKeyTyped
        // TODO add your handling code here:
       String banacc = txtBankAccNum.getText();
        String patter = "^[0-9]{0,11}+";
        Pattern exp = Pattern.compile(patter);
        Matcher match = exp.matcher(banacc);
        if(!match.matches()){
            lbErr.setText("Input should be 12 digits");
        }else{
            lbErr.setText(" ");
        }
    }//GEN-LAST:event_txtBankAccNumKeyTyped

    private void txtLicenseNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNumKeyTyped
        // TODO add your handling code here:
        String licenum = txtLicenseNum.getText();
        int len = licenum.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(len<8){
                txtLicenseNum.setEditable(true);
                lbErr.setText("Input should be 8 digits");
            }else{
                txtLicenseNum.setEditable(false);
                lbErr.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtLicenseNum.setEditable(true);
               
            }else{
                txtLicenseNum.setEditable(false);
                
            }
        }
    }//GEN-LAST:event_txtLicenseNumKeyTyped

    private void txtDeviceIdentifierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierKeyTyped
        // TODO add your handling code here:
       
        String devIdentifier = txtDeviceIdentifier.getText();
        int length = devIdentifier.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if(length<15){
                txtDeviceIdentifier.setEditable(true);
                lbErr.setText("Input should be 15 digits");
            }else{
                txtDeviceIdentifier.setEditable(false);
                lbErr.setText(" ");
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                txtDeviceIdentifier.setEditable(true);
               
            }else{
                txtDeviceIdentifier.setEditable(false);
                
            }
        }
    }//GEN-LAST:event_txtDeviceIdentifierKeyTyped

    private void txtIDCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDCodeKeyTyped
        // TODO add your handling code here:
        String idcode = txtIDCode.getText();
        int length = idcode.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='3')
        {
            if(length<4)
            {
                txtIDCode.setEditable(true);
                lbErr.setText("Input should be 4 digits");
            }
            else
            {
                txtIDCode.setEditable(false);
                lbErr.setText("Ivalid Format!");
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                txtIDCode.setEditable(true);
            }
            else
            {
                txtTelNum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtIDCodeKeyTyped

    private void txtIPAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddressKeyTyped
        // TODO add your handling code here:
        String ipa = txtIPAddress.getText();
        String digitRegEx = "(\\d{1,2}|(0|1)\\d{2}|2[0-4]\\d|25[0-5])";
        String ipRegEx = digitRegEx + "\\." + digitRegEx + "\\." + digitRegEx + "\\." + digitRegEx;
        Pattern pattern = Pattern.compile(ipRegEx);
        if(!pattern.matcher(ipa).matches())
        {
            lbErr.setText("Input invalid!");
        }else{
            lbErr.setText(" ");
        }
   
        
    }//GEN-LAST:event_txtIPAddressKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBioVal;
    private javax.swing.JButton btnImgSubmit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbAccNum;
    private javax.swing.JLabel lbBioImg;
    private javax.swing.JLabel lbBioVal;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbDeviceNum;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbErr;
    private javax.swing.JLabel lbFaxNum;
    private javax.swing.JLabel lbGeographicData;
    private javax.swing.JLabel lbHPBNum;
    private javax.swing.JLabel lbIDCode;
    private javax.swing.JLabel lbIPAddress;
    private javax.swing.JLabel lbImgSubmit;
    private javax.swing.JLabel lbLicenseNum;
    private javax.swing.JLabel lbLinkedIn;
    private javax.swing.JLabel lbMedicalRecNum;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhoto;
    private javax.swing.JLabel lbPlateNum;
    private javax.swing.JLabel lbSSN;
    private javax.swing.JLabel lbTelephoneNum;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField txtBankAccNum;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtFAXNum;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHPBNum;
    private javax.swing.JTextField txtIDCode;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPlateNum;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelNum;
    // End of variables declaration//GEN-END:variables

}