/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.CarDetailHistory;
import model.CarInfo;

/**
 *
 * @author fianrodrigues
 */
public class CreateJPanel extends javax.swing.JPanel
{

    /**
     * Creates new form CreateJPanel
     */
    CarDetailHistory history;
    public CreateJPanel(CarDetailHistory history) 
    {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbmake = new javax.swing.JLabel();
        lbmanufactureDate = new javax.swing.JLabel();
        lboccupancy = new javax.swing.JLabel();
        lbserialNumber = new javax.swing.JLabel();
        lbmodelNumber = new javax.swing.JLabel();
        lbcity = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtManufactureDate = new javax.swing.JTextField();
        txtOccupancy = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtCIty = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        lbmanufactureYear = new javax.swing.JLabel();
        txtManufactureYear = new javax.swing.JTextField();
        lbcertificate = new javax.swing.JLabel();
        txtCertificate = new javax.swing.JTextField();
        lbAvailability = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();

        lbmake.setText("Make:");

        lbmanufactureDate.setText("Manufacture Date:");

        lboccupancy.setText("Occupancy:");

        lbserialNumber.setText("Serial Number:");

        lbmodelNumber.setText("Model Number:");

        lbcity.setText("City:");

        txtManufactureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureDateActionPerformed(evt);
            }
        });

        txtOccupancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOccupancyActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        txtCIty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCItyActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lbTitle.setText("ADD CAR INFO");

        lbmanufactureYear.setText("Manufacture Year:");

        txtManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureYearActionPerformed(evt);
            }
        });

        lbcertificate.setText("Certificate:");

        txtCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificateActionPerformed(evt);
            }
        });

        lbAvailability.setText("Availability:");

        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbAvailability)
                    .addComponent(lbcertificate)
                    .addComponent(lbmanufactureYear)
                    .addComponent(lbcity)
                    .addComponent(lbmodelNumber)
                    .addComponent(lbserialNumber)
                    .addComponent(lboccupancy)
                    .addComponent(lbmanufactureDate)
                    .addComponent(lbmake))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSubmit)
                            .addComponent(txtMake, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(txtManufactureDate)
                            .addComponent(txtOccupancy)
                            .addComponent(txtSerialNumber)
                            .addComponent(txtModelNumber)
                            .addComponent(txtCIty)
                            .addComponent(txtManufactureYear)
                            .addComponent(txtCertificate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbmake)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmanufactureDate)
                    .addComponent(txtManufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lboccupancy)
                    .addComponent(txtOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbserialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmodelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcity)
                    .addComponent(txtCIty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbmanufactureYear)
                    .addComponent(txtManufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcertificate)
                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAvailability)
                    .addComponent(txtAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnSubmit)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
    
        
        String make = txtMake.getText();
        String date = txtManufactureDate.getText();
        int seats = Integer.parseInt(txtOccupancy.getText());
        long serialNumber = Long.parseLong(txtSerialNumber.getText());
        String modnum = txtModelNumber.getText();
        String city = txtCIty.getText();
        String year = txtManufactureYear.getText();
        String cert = txtCertificate.getText();
        String avail = txtAvailability.getText();

        
        CarInfo ci = history.addNewInfo();
        
        ci.setMake(make);
        ci.setManufactureDate(date);
        ci.setSeats(seats);
        ci.setSerialNumber(serialNumber);
        ci.setModelNumber(modnum);
        ci.setCity(city);
        ci.setManufactureYear(year);
        ci.setCertificate(cert);
        ci.setAvailability(avail);
        
        JOptionPane.showMessageDialog(this, "New Car Information Has Been Added");
        
        txtMake.setText("");
        txtManufactureDate.setText("");
        txtOccupancy.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCIty.setText("");
        txtManufactureYear.setText("");
        txtCertificate.setText("");
        txtAvailability.setText("");
     
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtOccupancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOccupancyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOccupancyActionPerformed

    private void txtManufactureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureDateActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void txtCItyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCItyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCItyActionPerformed

    private void txtManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureYearActionPerformed

    private void txtCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificateActionPerformed

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lbAvailability;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbcertificate;
    private javax.swing.JLabel lbcity;
    private javax.swing.JLabel lbmake;
    private javax.swing.JLabel lbmanufactureDate;
    private javax.swing.JLabel lbmanufactureYear;
    private javax.swing.JLabel lbmodelNumber;
    private javax.swing.JLabel lboccupancy;
    private javax.swing.JLabel lbserialNumber;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtCIty;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtManufactureDate;
    private javax.swing.JTextField txtManufactureYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtOccupancy;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
